function [file_keys,LFM1,LFM2,NMF1,NMF2,TNMF1,TNMF2,anchor] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FILE_KEYS,LFM1,LFM2,NMF1,NMF2,TNMF1,TNMF2,ANCHOR]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [FILE_KEYS,LFM1,LFM2,NMF1,NMF2,TNMF1,TNMF2,ANCHOR]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [file_keys,LFM1,LFM2,NMF1,NMF2,TNMF1,TNMF2,anchor] = importfile('-default-ratings.csv',2, 4);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/01/27 09:47:57

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
file_keys = dataArray{:, 1};
LFM1 = dataArray{:, 2};
LFM2 = dataArray{:, 3};
NMF1 = dataArray{:, 4};
NMF2 = dataArray{:, 5};
TNMF1 = dataArray{:, 6};
TNMF2 = dataArray{:, 7};
anchor = dataArray{:, 8};


